{
 "title": "Out of Band Node Details - open source version",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "query_result(count(up) by (job))"
   },
   {
    "name": "node",
    "query": "query_result(max_over_time(up{job=~\"$job\"}[14d]))"
   }
  ]
 },
 "panels": [
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature Sensors (non DIMM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "bmc_temperature_celsius{instance=\"$node\", sensor!~\"DIMM.*\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "max(bmc_temperature_celsius{instance=\"$node\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(bmc_temperature_celsius{instance=\"$node\"}) by (sensor)",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "max(bmc_temperature_celsius_ok{instance=\"$node\"}) by (sensor)",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Temperature Sensors (DIMM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "bmc_temperature_celsius{instance=\"$node\", sensor=~\"DIMM.*\"}",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "max(bmc_temperature_celsius{instance=\"$node\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "FAN Speeds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "FAN Speeds (RPM)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "[RPM]" }
   ],
   "targets": [
    {
     "expr": "bmc_fan_speed_rpm{instance=\"$node\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "FAN Speeds (Percent) - OpenBmc Only",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "bmc_fan_speed_percent{instance=\"$node\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "FAN Speeds (RPM)",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max(bmc_fan_speed_rpm_ok{instance=\"$node\"}) by (sensor)",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "max(bmc_fan_speed_rpm{instance=\"$node\"}) by (sensor)",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "FAN Speeds (Percent) - OpenBmc Only",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "max(bmc_fan_speed_percent_ok{instance=\"$node\"}) by (sensor)",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "max(bmc_fan_speed_percent{instance=\"$node\"}) by (sensor)",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Voltages",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "expr": "bmc_voltage_volts{instance=\"$node\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Voltage Sensors",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "max(bmc_voltage_volts{instance=\"$node\"}) by (sensor)",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "max(bmc_voltage_volts_ok{instance=\"$node\"}) by (sensor)",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  }
 ]
}