apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openbmc-prometheus-exporter.fullname" . }}
  labels:
{{ include "openbmc-prometheus-exporter.labels" . | indent 4 }}
data:
  configyaml: |-
{{ .Values.configuration | indent 4 }}
