{{- if .Values.credentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openbmc-prometheus-exporter.fullname" . }}
  labels:
{{ include "openbmc-prometheus-exporter.labels" . | indent 4 }}
type: Opaque
data:
  "openbmc-credentials.yaml": {{ .Values.credentials | b64enc }}
{{- end }}
